In [1]:
import torch

In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [3]:
torch.manual_seed(7)

features = torch.randn((1, 5))
weights = torch.randn_like(features)
bias = torch.randn((1, 1))

In [4]:
y = activation(torch.sum(features*weights)+bias)


In [5]:
y

tensor([[0.1595]])

In [6]:
weights.shape

torch.Size([1, 5])

In [7]:
 weights=weights.reshape(5,1)

In [8]:
weights.shape

torch.Size([5, 1])

In [9]:
act = activation(torch.mm(features,weights)+ bias)

In [10]:
act

tensor([[0.1595]])

In [11]:
torch.manual_seed(7) 

features = torch.randn((1, 3))


n_input = features.shape[1]   
n_hidden = 2                  
n_output = 1

W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [13]:
conn = activation(torch.mm(features,W1)+B1)


In [14]:
out = activation(torch.mm(conn,W2)+B2)

In [15]:
out

tensor([[0.3171]])

In [16]:


import numpy as np
a = np.random.rand(4,3)
a



array([[0.03620049, 0.57996689, 0.76579242],
       [0.78095848, 0.47987559, 0.25040135],
       [0.21916335, 0.90146129, 0.16080894],
       [0.9133641 , 0.74629672, 0.164909  ]])

In [17]:


b = torch.from_numpy(a)
b



tensor([[0.0362, 0.5800, 0.7658],
        [0.7810, 0.4799, 0.2504],
        [0.2192, 0.9015, 0.1608],
        [0.9134, 0.7463, 0.1649]], dtype=torch.float64)

In [18]:
b.numpy()

array([[0.03620049, 0.57996689, 0.76579242],
       [0.78095848, 0.47987559, 0.25040135],
       [0.21916335, 0.90146129, 0.16080894],
       [0.9133641 , 0.74629672, 0.164909  ]])